####################################################
#                                                  #
#  This file is used for testing                   #
#  Used by REST Client extensions in VSCode        #
#                                                  # 
####################################################


@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzA3NjU2NzAsImlzcyI6Imx1dXRoYW5oZGF0In0.g6ni3vUde6Tkj2JcRQ3mFD6ZMIR7-ybEFgs-ubBMw-Q

@base_url = http://127.0.0.1:8080

@api_url = {{base_url}}/api/v1

########################
#    1. User Module    #
########################


### User Register
POST {{api_url}}/register HTTP/1.1
content-type: application/json

{
    "username": "luuthanhdat12",
    "email": "datluu.1702123@gmail.com",
    "password": "dat123!@#",
    "age": 19,
    "Gender": 0
}


### User Login
POST {{api_url}}/login HTTP/1.1
content-type: application/json

{   
    "username": "luuthanhdat",
    "password": "dat123!@#"
}


### User GetAll
GET {{api_url}}/user HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### User GetOne
GET {{api_url}}/user/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### User Delete
DELETE {{api_url}}/user/2 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### User Update
PUT {{api_url}}/user/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "age": 20
}


### User Auth
Get {{api_url}}/user/check_auth HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}



########################
#    2. Todo Module    #
########################


### Todo Add
POST {{api_url}}/todo HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "name": "task 1",
    "description": "description of task 1",
    "user_id": 1,
    "status": "Active"
}


### Todo GetAll
GET {{api_url}}/todo HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


### Todo GetOne
GET {{api_url}}/todo/2 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

### Todo Update
PUT {{api_url}}/todo/2 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "name": "task 1"
}


### Todo Delete
DELETE {{api_url}}/todo/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}
