####################################################
#                                                  #
#  This file is used for testing                   #
#  Used by REST Client extensions in VSCode        #
#                                                  # 
####################################################


@access_token = {{user_login.response.body.data.access_token}}
@base_url = http://127.0.0.1:8080
@api_url = {{base_url}}/api/v1


########################
#    1. User Module    #
########################


### User Register ###
# @name user_register
POST {{api_url}}/register HTTP/1.1
content-type: application/json

{
    "username": "luuthanhdat12",
    "email": "datluu.1702123@gmail.com",
    "password": "dat123!@#",
    "age": 19,
    "Gender": 0
}



### User Login ###
# @name user_login
POST {{api_url}}/login HTTP/1.1
content-type: application/json

{   
    "username": "luuthanhdat",
    "password": "dat123!@#"
}



### User Get All ###
# @name user_getall
GET {{api_url}}/user HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}



### User Get One ###
# @name user_getone
GET {{api_url}}/user/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}



### User Delete ###
# @name user_delete
DELETE {{api_url}}/user/2 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}



### User Update ###
# @name user_update
PUT {{api_url}}/user/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "age": 20
}



### User Check Auth ###
# @name user_auth
Get {{api_url}}/user/check_auth HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}



########################
#    2. Todo Module    #
########################


### Todo Create ###
# @name todo_create
POST {{api_url}}/todo HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "name": "task 1",
    "description": "description of task 1",
    "user_id": 1,
    "status": "Active"
}



### Todo Get All ###
# @name todo_getall
GET {{api_url}}/todo HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}



### Todo Get One ###
# @name todo_getone
GET {{api_url}}/todo/2 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}



### Todo Update ###
# @name todo_update
PUT {{api_url}}/todo/2 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "name": "task 1"
}



### Todo Delete ###
# @name todo_delete
DELETE {{api_url}}/todo/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}
